apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: aakarshak1/ems-app
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: "mysqldb-service"  # Use the service name instead of the pod name
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "assign"
            - name: MYSQL_USER
              value: "tnm"
            - name: MYSQL_PASSWORD
              value: "password"

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-app-to-db
spec:
  podSelector:
    matchLabels:
      app: app
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: mysqldb
  policyTypes:
    - Ingress
