version: 0.2

phases:
  #      For CodeDeploy part only
  install:
    runtime-versions:
      java: corretto17
  #      To this
  build:
    commands:
      - echo "Packaging JAR file..."
      - mvn clean package
    finally:
      - echo "Build phase complete."

artifacts:
  files:
    - target/EmployeeManagementSystem.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
