version: 0.2
phases:
  build:
    commands:
      -echo Packaging JAR file...
      - mvn clean package
    post-build:
      commands:
        -echo Build complete.
artifacts:
  files:
    -target/EmployeeManagementSystem.jar
  discard-paths: yes