version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=assign
      - MYSQL_USER=tnm
      - MYSQL_PASSWORD=password
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net

  mysqldb:
    image: mysql/mysql-server:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=assign
      - MYSQL_USER=tnm
      - MYSQL_PASSWORD=password
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge
